title: Computer Graphics Repository
description: Github Repository Collection of Computer Graphics
logo: /assets/img/logo.png
author: David Kuo
author_link: https://crescent3983.github.io/about

baseurl: /GraphicsRepoCollection
url: https://crescent3983.github.io

google_analytics: G-HV6MGLDKED

enableTags: true

markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]