title: Computer Graphics Repository
description: Github Repository Collection of Computer Graphics
author: David Kuo
logo: /assets/img/logo.png

baseurl: /GraphicsRepoCollection
url: https://crescent3983.github.io

linkedin: david-kuo-21707a236
google_analytics: G-HV6MGLDKED

enableTags: true

markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]