title: Graphics Repository Collection
description: Github Repository Collection of Computer Graphics
author: David Kuo
linkedin: david-kuo-21707a236

baseurl: "/GraphicsRepoCollection"
url: "https://crescent3983.github.io"

google_analytics: 

enableTags: true

markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]